// Generated by CoffeeScript 1.3.3
var FB, app, express, http, port, request, server, ss;

http = require("http");

express = require("express");

request = require("request");

FB = require('fb');

ss = require("socketstream");

ss.client.define("main", {
  view: "app.jade",
  css: ["libs", "app.styl"],
  code: ["libs", "app", "system"],
  tmpl: "*"
});

FB.setAccessToken('access_token');

app = express.createServer(ss.http.middleware, express.logger(), express.bodyParser(), express.cookieParser(), express.session({
  secret: "ILoveP2"
}));

app.all("/", function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "X-Requested-With");
  return next();
});

app.get("/", function(req, res) {
  return res.serve("main");
});

app.post("/", function(req, res) {
  return res.serve("main");
});

app.get("/thumb/:file", function(req, res) {
  return res.redirect("http://i.imgur.com/" + req.params.file);
});

app.get("/full/:file", function(req, res) {
  return res.redirect("http://i.imgur.com/" + req.params.file);
});

app.get("/gallery/:file", function(req, res) {
  var params;
  params = req.params.file.replace(/\:/g, '/') + ".json";
  return request.get("http://api.imgur.com/2/album/" + params).pipe(res);
});

ss.client.formatters.add(require("ss-coffee"));

ss.client.formatters.add(require("ss-jade"));

ss.client.formatters.add(require("ss-stylus"));

ss.client.templateEngine.use(require("ss-hogan"));

if (ss.env === "production") {
  ss.client.packAssets();
}

ss.ws.transport.use(require('ss-sockjs'));

app.stack = app.stack.concat(ss.http.middleware.stack);

ss.publish.transport.use('redis', {
  host: 'tetra.redistogo.com',
  port: 9461,
  user: 'nodejitsu',
  pass: 'cd55e4fc7ee4a4b93386ec5d89ec8346',
  db: 1
});

ss.session.store.use('redis', {
  host: 'tetra.redistogo.com',
  port: 9461,
  user: 'nodejitsu',
  pass: 'cd55e4fc7ee4a4b93386ec5d89ec8346',
  db: 1
});

port = process.env.PORT || 3000;

server = app.listen(port);

ss.start(server);
