// Generated by CoffeeScript 1.3.3
var Galleries, Gallery, GalleryMain, Images, P2,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

P2 = require('p2');

Gallery = require('/models/gallery');

Galleries = require('/controllers/galleries');

Images = require('/controllers/images');

GalleryMain = (function(_super) {

  __extends(GalleryMain, _super);

  GalleryMain.prototype.className = 'main';

  GalleryMain.prototype.elements = {
    'aside': 'formHolder',
    'form': 'form',
    '.images-wrapper': 'imgHolder',
    'footer .submit': 'footer',
    '.gallery-wrapper': 'galleryHolder',
    '.message': 'message',
    '.loader': 'loader'
  };

  GalleryMain.prototype.events = {
    'click .green': 'formHandle',
    'click .red': 'back'
  };

  function GalleryMain() {
    this.back = __bind(this.back, this);

    this.formHandle = __bind(this.formHandle, this);

    this.checkIma = __bind(this.checkIma, this);

    this.launchEditor = __bind(this.launchEditor, this);

    var _this = this;
    GalleryMain.__super__.constructor.apply(this, arguments);
    this.galleries = new Galleries;
    this.images = new Images;
    ss.event.on('postSuccess', function(res) {
      var mess;
      P2.trigger('loader.hide');
      mess = ss.tmpl['gallery-posted'].render({
        message: message.id
      });
      _this.imgHolder.prepend(mess);
      return $('.message').last().slideDown().delay(5000).fadeOut(500, function() {
        return $('.message').remove();
      });
    });
    ss.event.on('auth', function(userId) {
      _this.userId = userId;
      _this.message.fadeOut();
      _this.append(_this.images);
      _this.append(_this.galleries);
      return $('#fb-login').fadeOut();
    });
    P2.bind('loader.show', function() {
      return _this.loadder.fadeIn();
    });
    P2.bind('loader.hide', function() {
      return _this.loader.fadeOut();
    });
    P2.bind('gallery.show', function() {
      _this.formHolder.slideUp();
      _this.imgHolder.fadeIn();
      return _this.footer.hide();
    });
    P2.bind('gallery.form', function(imgurl, title) {
      _this.imgUrl = imgurl;
      $('footer .submit').show();
      _this.imgHolder.fadeOut();
      _this.galleryHolder.fadeOut();
      _this.formHolder.find('img').remove();
      return _this.formHolder.append("<img src='" + imgurl + "' id='featherimage'/>").slideDown(500, function() {
        _this.launchEditor('featherimage', _this.imgUrl);
        _this.footer.fadeIn();
        _this.formHolder.css('overflow-y', 'auto');
        return _this.formHolder.find('.message').text(title);
      });
    });
    this.render();
  }

  GalleryMain.prototype.launchEditor = function(id, src) {
    featherEditor.launch({
      image: id,
      url: src
    });
    $("#" + id).hide();
    return this.checkIma();
  };

  GalleryMain.prototype.checkIma = function(id, src) {
    var _this = this;
    return setTimeout(function() {
      var ima;
      ima = $('#avpw_aviary_about');
      if (ima.length > 0) {
        return ima.remove();
      } else {
        return _this.checkIma;
      }
    }, 500);
  };

  GalleryMain.prototype.formHandle = function(e) {
    var imgUrl;
    e.preventDefault();
    this.imgHolder.fadeIn();
    this.galleryHolder.fadeIn();
    this.formHolder.fadeOut();
    this.footer.fadeOut();
    $('#posttowall').hide();
    imgUrl = $('#featherimage').attr('src');
    return ss.rpc('user.makePost', imgUrl, function() {
      return P2.trigger('loader.show');
    });
  };

  GalleryMain.prototype.back = function() {
    var _this = this;
    this.imgHolder.show();
    this.galleryHolder.fadeIn();
    $('footer .submit').hide();
    this.imgHolder.scrollTo('.current');
    this.formHolder.slideUp();
    this.footer.fadeOut();
    this.imgHolder.find('.last').waypoint(function(e, dir) {
      return _this.loadgallery();
    }, {
      triggerOnce: true,
      context: '.images-wrapper',
      offset: '100%'
    });
    $('#posttowall').hide();
    return featherEditor.close();
  };

  GalleryMain.prototype.render = function() {
    this.append(ss.tmpl['gallery-login'].render());
    return this.append(ss.tmpl['gallery-footer'].render());
  };

  return GalleryMain;

})(P2.Controller);

module.exports = GalleryMain;
