// Generated by CoffeeScript 1.3.3
var FB, request;

request = require('request');

FB = require('fb');

exports.actions = function(req, res, ss) {
  req.use('session');
  return {
    auth: function(authdata) {
      if (!authdata.accessToken) {
        return;
      }
      req.session.fb = authdata;
      FB.options({
        accessToken: authdata.accessToken
      });
      return FB.api('/me', function(response) {
        if (response != null ? response.error : void 0) {
          return;
        }
        req.session.setUserId(response.username);
        return ss.publish.user(req.session.userId, 'auth', req.session.userId);
      });
    },
    checkLike: function() {
      return FB.api('/me/likes', function(response) {
        console.log(response);
        if (response != null ? response.error : void 0) {
          return;
        }
        req.session.setUserId(response.username);
        return ss.publish.user(req.session.userId, 'auth', req.session.userId);
      });
    },
    makePost: function(imgUrl, message) {
      FB.options({
        accessToken: req.session.fb.accessToken
      });
      return FB.api("/" + req.session.userId + "/photos", "post", {
        name: "" + message + " - Tạo status độc tại https://apps.facebook.com/fb-jstest/",
        url: "" + imgUrl
      }, function(response) {
        if (response != null ? response.error : void 0) {
          return;
        }
        return ss.publish.user(req.session.userId, 'postSuccess', response);
      });
    }
  };
};
